name: Generate ePUB
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pakohan/cooklang-epub@8af5f4547494f2273450a37a41d6fc3bf5e92f9a
