name: Generate ePUB
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Checkout template
        uses: actions/checkout@v4
        with:
          repository: "pakohan/cooklang-epub-template"
          path: "templates"
      - name: Generate ePUB
        uses: pakohan/cooklang-epub@v1.0.0
      - name: Delete previous book
        uses: sgpublic/delete-release-action@v1.2
        with:
          release-drop: true
          release-keep-count: 0
          release-drop-tag: true
      - name: Upload new ePUB
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          tag_name: "book"
          files: ./recipes.epub
