name: Generate ePUB
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Checkout template
        uses: actions/checkout@v4
        with:
          repository: "pakohan/cooklang-epub-template"
          path: "templates"
      - name: Generate ePUB
        uses: pakohan/cooklang-epub@v3.0.0
      - name: Delete previous book
        uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 0
          keep-old-minor-releases: false
          keep-old-minor-releases-count: 0
      - name: Upload new ePUB
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          tag_name: "1"
          files: ./recipes.epub
      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Actions job result
          to: ${{ secrets.EMAIL_ADDRESS }}
          from: Patrick Kohan
          attachments: ./recipes.epub
