name: Generate ePUB
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "pakohan/cooklang-epub-template"
          path: "templates"
      - uses: pakohan/cooklang-epub@v1.0.0
      - name: upload epub
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          files: ./recipes.epub
